import express from "express";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";

const router = express.Router();

router.post("/login", async (req, res) => {
  const { email, password } = req.body || {};
  if (!email || !password) return res.status(400).json({ message: "Email and password are required." });

  const configuredEmail = (process.env.ADMIN_EMAIL || "").trim().toLowerCase();
  const configuredHash = process.env.ADMIN_PASSWORD_HASH || "";

  if (!configuredEmail || !configuredHash || !process.env.JWT_SECRET) {
    return res.status(503).json({ message: "Admin authentication is not configured on the server." });
  }

  // ADMIN_PASSWORD_HASH must be a bcrypt hash generated by
  // `npm run hash-password` (server/scripts/hashPassword.js), not the
  // plain-text password itself. A plain-text value here will silently
  // make every login attempt fail with "Invalid admin credentials",
  // even when the password typed in is correct.
  if (!/^\$2[aby]\$/.test(configuredHash)) {
    console.warn(
      "[auth] ADMIN_PASSWORD_HASH does not look like a bcrypt hash. " +
      "Run `npm run hash-password` in /server and paste the generated hash " +
      "(starts with $2a$, $2b$ or $2y$) into ADMIN_PASSWORD_HASH in server/.env, then restart the server."
    );
  }

  const validEmail = email.trim().toLowerCase() === configuredEmail;
  const validPassword = await bcrypt.compare(password, configuredHash);

  if (!validEmail || !validPassword) return res.status(401).json({ message: "Invalid admin credentials." });

  const token = jwt.sign(
    { role: "admin", email: configuredEmail },
    process.env.JWT_SECRET,
    { expiresIn: "8h" }
  );

  res.json({ token, admin: { email: configuredEmail, role: "admin" } });
});

export default router;
